name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - root

jobs:
  github-pages:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: update
        run: sudo apt-get update
      - name: install/libmagickwand
        run: sudo apt-get install -y libmagickwand-dev
      - name: install/imagemagick
        run: sudo apt-get install -y graphicsmagick-imagemagick-compat --fix-missing
      - uses: jeffreytse/jekyll-deploy-action@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
