name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - root

jobs:
  github-pages:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: actions/setup-node@v3
      - name: preprocess
        run: |
          npm install 
          node preprocessor.js
      - uses: jeffreytse/jekyll-deploy-action@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
