name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - root

jobs:
  github-pages:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: jeffreytse/jekyll-deploy-action@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
